export const LOL_CHAMP_LIST_REQUEST = "LOL_CHAMP_LIST_REQUEST";
export const LOL_CHAMP_LIST_SUCCESS = "LOL_CHAMP_LIST_SUCCESS";
export const LOL_CHAMP_LIST_FAIL = "LOL_CHAMP_LIST_FAIL";

export const LOL_CHAMP_DETAILS_REQUEST = "LOL_CHAMP_DETAILS_REQUEST";
export const LOL_CHAMP_DETAILS_SUCCESS = "LOL_CHAMP_DETAILS_SUCCESS";
export const LOL_CHAMP_DETAILS_FAIL = "LOL_CHAMP_DETAILS_FAIL";

export const LOL_CHAMP_CREATE_REQUEST = "LOL_CHAMP_CREATE_REQUEST";
export const LOL_CHAMP_CREATE_SUCCESS = "LOL_CHAMP_CREATE_SUCCESS";
export const LOL_CHAMP_CREATE_FAIL = "LOL_CHAMP_CREATE_FAIL";
export const LOL_CHAMP_CREATE_RESET = "LOL_CHAMP_CREATE_RESET";
