export const VALORANT_CHAMP_LIST_REQUEST = "VALORANT_CHAMP_LIST_REQUEST";
export const VALORANT_CHAMP_LIST_SUCCESS = "VALORANT_CHAMP_LIST_SUCCESS";
export const VALORANT_CHAMP_LIST_FAIL = "VALORANT_CHAMP_LIST_FAIL";

export const VALORANT_CHAMP_DETAILS_REQUEST = "VALORANT_CHAMP_DETAILS_REQUEST";
export const VALORANT_CHAMP_DETAILS_SUCCESS = "VALORANT_CHAMP_DETAILS_SUCCESS";
export const VALORANT_CHAMP_DETAILS_FAIL = "VALORANT_CHAMP_DETAILS_FAIL";

export const VALORANT_CHAMP_CREATE_REQUEST = "VALORANT_CHAMP_CREATE_REQUEST";
export const VALORANT_CHAMP_CREATE_SUCCESS = "VALORANT_CHAMP_CREATE_SUCCESS";
export const VALORANT_CHAMP_CREATE_FAIL = "VALORANT_CHAMP_CREATE_FAIL";
export const VALORANT_CHAMP_CREATE_RESET = "VALORANT_CHAMP_CREATE_RESET";
